### ISSUE TITLE
makefile should return exit code on fail

### ISSUE THREAD

**Issue by mattvenn** [matt-beach/wrapped_memLCDdriver#1]
copy the ! grep results line from your caravel makefile to all the other cocotb recipes you have in the other makefiles.
then if the tests fail, the multi project tools will know

**Comment by matt-beach** [comment]
Added '! grep failure results.xml' for each test in memLCDdriver Makefile. mulit_tool.py succeeds locally, and each coco_test reports the '! grep failure results.xml' under it.
